name: Python environment setup ðŸ
description: "Setup Python environment and install dependencies with poetry."

runs:
  using: "composite"

  steps:
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: "poetry"
    - name: Install poetry
      shell: bash
      run: |
        curl -sSL https://install.python-poetry.org | python
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    - name: Install dependencies
      shell: bash
      run: |
        poetry install
